apiVersion: v1
kind: Service
metadata:
  name: example-app-service
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: dms
spec:
  type: NodePort
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002