name: Build and push Docker image from lab 3

on:
  push:
    branches:
      - master
    paths:
      - 'lab-3-advanced/example-app/**'
      - '.github/workflows/docker_image_lab_3_advanced.yml'

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://127.0.0.1:8200
          tlsSkipVerify: true
          token: \${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/dockerhub-workflow DOCKER_HUB_USERNAME ;
            secret/data/dockerhub-workflow DOCKER_HUB_ACCESS_TOKEN
      - uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./lab-3-advanced/example-app
          push: true
          tags: tfsiva/example-app:latest , tfsiva/example-app:${{ github.run_number }}
