name: Build and push Docker image from lab 3

on:
  push:
    branches:
      - master
    paths:
      - 'lab-3/example-app/**'
      - '.github/workflows/docker_image_lab_3.yml'

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./lab-3/example-app
          push: true
          tags:
            tfsiva/example-app:latest
            tfsiva/example-app:${{ github.run_number }}
